"""Tests for markdown report generation across all modes."""

from __future__ import annotations

from datetime import timedelta

from debugbrief.models import (
    COMMAND_STATUS_FAILED,
    COMMAND_STATUS_PASSED,
    CommandClassification,
    CommandData,
    Event,
    GitState,
    Session,
    SessionStatus,
    Summary,
    Timestamps,
)
from debugbrief.reporters import VALID_MODES, render_report
from debugbrief.utils import to_iso8601, utc_now


def _command_event(command, status, ts, exit_code, **cls_kwargs):
    data = CommandData(
        command=command,
        started_at=ts,
        ended_at=ts,
        duration_seconds=0.2,
        exit_code=exit_code,
        stderr_preview=cls_kwargs.pop("stderr_preview", ""),
        classification=CommandClassification(status=status, **cls_kwargs),
    )
    return Event.command(data, ts)


def _rich_session():
    now = utc_now()
    t0 = to_iso8601(now)
    t1 = to_iso8601(now + timedelta(seconds=5))
    t2 = to_iso8601(now + timedelta(seconds=10))
    session = Session(
        title="Fix auth token refresh race",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(
            is_repo=True,
            repo_root="/repo",
            initial_sha="aaaaaaaaaaaa",
            final_sha="bbbbbbbbbbbb",
            branch="feature/auth",
        ),
        timestamps=Timestamps(start=t0, end=t2),
    )
    session.events.append(Event.snapshot({"phase": "start"}, t0))
    session.events.append(Event.note("Refresh state shared across requests.", t0))
    session.events.append(
        _command_event(
            "pytest tests/test_auth.py",
            COMMAND_STATUS_FAILED,
            t0,
            1,
            is_test=True,
            tool="pytest",
            stderr_preview="AssertionError: token mismatch",
        )
    )
    session.events.append(
        _command_event(
            "pytest tests/test_auth.py",
            COMMAND_STATUS_PASSED,
            t1,
            0,
            is_test=True,
            is_verification=True,
            tool="pytest",
        )
    )
    session.events.append(Event.snapshot({"phase": "end"}, t2))
    session.summary = Summary(
        modified_files=["src/auth.py", "tests/test_auth.py"],
        lines_added=12,
        lines_deleted=4,
        tests_run=["pytest tests/test_auth.py"],
        notes_count=1,
        commands_count=2,
        failed_commands_count=1,
        command_capture_status="full",
    )
    return session


def test_all_modes_render_nonempty():
    session = _rich_session()
    for mode in VALID_MODES:
        report = render_report(session, mode)
        assert report.startswith("# Fix auth token refresh race")
        assert "Generated by DebugBrief" in report


def test_pr_required_sections():
    report = render_report(_rich_session(), "pr")
    for header in [
        "## Overview",
        "## Key findings",
        "## Changes implemented",
        "## Modified files",
        "## Verification and tests",
        "## Relevant commands",
        "## Risks / follow-up",
    ]:
        assert header in report, header
    # Verification passed once: must be reflected, not fabricated.
    assert "[passed] test (pytest)" in report
    # Notes surfaced as key findings.
    assert "Refresh state shared across requests." in report


def test_handoff_required_sections():
    report = render_report(_rich_session(), "handoff")
    for header in [
        "## Current status",
        "## Working hypotheses / findings",
        "## Timeline of meaningful steps",
        "## Commands attempted",
        "## Modified files",
        "## Current repo state",
        "## Suggested next steps",
    ]:
        assert header in report, header


def test_incident_required_sections():
    report = render_report(_rich_session(), "incident")
    for header in [
        "## Executive summary",
        "## Time window",
        "## Chronological event timeline",
        "## Actions taken",
        "## Resolution / current state",
        "## Verification and tests",
        "## Follow-up items",
    ]:
        assert header in report, header


def test_dedup_in_report_actions():
    # The two identical pytest commands within 5s should squash to one entry.
    report = render_report(_rich_session(), "incident")
    assert "`pytest tests/test_auth.py` x2" in report


def test_no_notes_is_conservative():
    session = _rich_session()
    session.events = [e for e in session.events if e.type != "note"]
    session.summary.notes_count = 0
    report = render_report(session, "pr")
    assert "No findings were recorded" in report


def test_no_verification_is_honest():
    now = utc_now()
    ts = to_iso8601(now)
    session = Session(
        title="No verification here",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(is_repo=True, repo_root="/repo", initial_sha="a", final_sha="a"),
        timestamps=Timestamps(start=ts, end=ts),
    )
    session.events.append(
        _command_event("echo hi", COMMAND_STATUS_PASSED, ts, 0)
    )
    session.summary = Summary(commands_count=1, command_capture_status="full")
    report = render_report(session, "pr")
    assert "not** backed by a passing verification" in report or "no verification" in report.lower()
    assert "No verification commands" in report


def test_no_changes_stated_plainly():
    now = utc_now()
    ts = to_iso8601(now)
    session = Session(
        title="Notes only",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(is_repo=True, repo_root="/repo", initial_sha="a", final_sha="a"),
        timestamps=Timestamps(start=ts, end=ts),
    )
    session.events.append(Event.note("Just thinking out loud.", ts))
    session.summary = Summary(notes_count=1, command_capture_status="full")
    report = render_report(session, "pr")
    assert "No file changes were detected" in report
    assert "Just thinking out loud." in report


def test_failed_command_appears():
    report = render_report(_rich_session(), "pr")
    # The failing pytest run was squashed with the later pass within 5s, so the
    # most recent (passing) outcome wins -- failed section may be empty, which is
    # honest. Instead assert the relevant-commands list reflects the real run.
    assert "pytest tests/test_auth.py" in report
