"""Tests for markdown report generation across all modes."""

from __future__ import annotations

from datetime import timedelta

from debugbrief.models import (
    COMMAND_STATUS_FAILED,
    COMMAND_STATUS_PASSED,
    CommandClassification,
    CommandData,
    Event,
    GitState,
    Session,
    SessionStatus,
    Summary,
    Timestamps,
)
from debugbrief.reporters import VALID_MODES, render_report
from debugbrief.utils import to_iso8601, utc_now


def _command_event(command, status, ts, exit_code, changed_files=None, **cls_kwargs):
    data = CommandData(
        command=command,
        started_at=ts,
        ended_at=ts,
        duration_seconds=0.2,
        exit_code=exit_code,
        stderr_preview=cls_kwargs.pop("stderr_preview", ""),
        classification=CommandClassification(status=status, **cls_kwargs),
        git_changed_files=list(changed_files or []),
    )
    return Event.command(data, ts)


def _rich_session():
    now = utc_now()
    t0 = to_iso8601(now)
    t1 = to_iso8601(now + timedelta(seconds=5))
    t2 = to_iso8601(now + timedelta(seconds=10))
    session = Session(
        title="Fix auth token refresh race",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(
            is_repo=True,
            repo_root="/repo",
            initial_sha="aaaaaaaaaaaa",
            final_sha="bbbbbbbbbbbb",
            branch="feature/auth",
        ),
        timestamps=Timestamps(start=t0, end=t2),
    )
    session.events.append(Event.snapshot({"phase": "start"}, t0))
    session.events.append(Event.note("Refresh state shared across requests.", t0))
    session.events.append(
        _command_event(
            "pytest tests/test_auth.py",
            COMMAND_STATUS_FAILED,
            t0,
            1,
            changed_files=["src/auth.py"],
            is_test=True,
            tool="pytest",
            stderr_preview="AssertionError: token mismatch",
        )
    )
    session.events.append(
        _command_event(
            "pytest tests/test_auth.py",
            COMMAND_STATUS_PASSED,
            t1,
            0,
            changed_files=["src/auth.py", "tests/test_auth.py"],
            is_test=True,
            is_verification=True,
            tool="pytest",
        )
    )
    session.events.append(Event.snapshot({"phase": "end"}, t2))
    session.summary = Summary(
        modified_files=["src/auth.py", "tests/test_auth.py"],
        lines_added=12,
        lines_deleted=4,
        tests_run=["pytest tests/test_auth.py"],
        notes_count=1,
        commands_count=2,
        failed_commands_count=1,
        command_capture_status="full",
    )
    return session


def test_all_modes_render_nonempty():
    session = _rich_session()
    for mode in VALID_MODES:
        report = render_report(session, mode)
        assert report.startswith("# Fix auth token refresh race")
        assert "Generated by DebugBrief" in report


def test_pr_required_sections():
    report = render_report(_rich_session(), "pr")
    for header in [
        "## Summary",
        "## Reproduce and verify",
        "## Red to green",
        "## Modified files",
        "## Timeline",
        "## Verification and tests",
        "## Failed attempts",
    ]:
        assert header in report, header
    # Derived one-liner reflects the real transition, not a templated overview.
    assert "Failing check `pytest tests/test_auth.py` passed" in report
    # Verification passed once: must be reflected, not fabricated.
    assert "[passed] test (pytest)" in report
    # Removed templated sections must be gone.
    assert "## Overview" not in report
    assert "## Risks / follow-up" not in report
    assert "No outstanding risks were detected" not in report


def test_pr_red_to_green_correlates_files():
    report = render_report(_rich_session(), "pr")
    assert "correlation, not proven cause" in report
    assert "`src/auth.py`" in report
    # Honest phrasing: never claims the files fixed it.
    assert "fixed" not in report.lower()


def test_handoff_required_sections():
    report = render_report(_rich_session(), "handoff")
    for header in [
        "## Current status",
        "## Working hypotheses / findings",
        "## Timeline",
        "## Commands attempted",
        "## Current repo state",
    ]:
        assert header in report, header


def test_incident_required_sections():
    report = render_report(_rich_session(), "incident")
    for header in [
        "## Time window",
        "## Chronological event timeline",
        "## Observed error",
        "## Resolution / current state",
        "## Verification and tests",
    ]:
        assert header in report, header
    # Observed error is quoted verbatim from real stderr.
    assert "AssertionError: token mismatch" in report


def test_dedup_in_report_actions():
    # The two identical pytest commands within 5s should squash to one entry in
    # the deduplicated command list (Commands attempted), even though the raw
    # timeline keeps both.
    report = render_report(_rich_session(), "handoff")
    assert "`pytest tests/test_auth.py` x2" in report


def test_no_notes_does_not_fabricate():
    session = _rich_session()
    session.events = [e for e in session.events if e.type != "note"]
    session.summary.notes_count = 0
    report = render_report(session, "pr")
    # The report still renders and never invents findings.
    assert report.startswith("# Fix auth token refresh race")
    assert "## Timeline" in report


def test_no_verification_is_honest():
    now = utc_now()
    ts = to_iso8601(now)
    session = Session(
        title="No verification here",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(is_repo=True, repo_root="/repo", initial_sha="a", final_sha="a"),
        timestamps=Timestamps(start=ts, end=ts),
    )
    session.events.append(
        _command_event("echo hi", COMMAND_STATUS_PASSED, ts, 0)
    )
    session.summary = Summary(commands_count=1, command_capture_status="full")
    report = render_report(session, "pr")
    assert "no verification commands were run" in report.lower()
    assert "No verification commands" in report


def test_no_changes_omits_modified_files():
    now = utc_now()
    ts = to_iso8601(now)
    session = Session(
        title="Notes only",
        project_root="/repo",
        status=SessionStatus.COMPLETED.value,
        git=GitState(is_repo=True, repo_root="/repo", initial_sha="a", final_sha="a"),
        timestamps=Timestamps(start=ts, end=ts),
    )
    session.events.append(Event.note("Just thinking out loud.", ts))
    session.summary = Summary(notes_count=1, command_capture_status="full")
    report = render_report(session, "pr")
    # With no file changes the section is omitted, not padded with filler.
    assert "## Modified files" not in report
    # Notes still surface in the timeline.
    assert "Just thinking out loud." in report


def test_compact_pr_report_collapses_heavy_sections():
    session = _rich_session()
    full = render_report(session, "pr", detail="full")
    compact = render_report(session, "pr", detail="compact")
    # The default is unchanged: no collapsible section.
    assert "<details>" not in full
    # Compact keeps the scannable parts visible and folds the rest away.
    assert "<details>" in compact
    head = compact.split("<details>")[0]
    assert "## Summary" in head  # the derived one-liner stays up top
    assert "## Session metadata" not in head  # metadata is folded in
    assert "## Session metadata" in compact  # but still present, just collapsed
    # The visible (non-collapsed) part is much shorter than the full report.
    assert len(head) < len(full)


def test_failed_command_is_listed_as_a_failed_attempt():
    report = render_report(_rich_session(), "pr")
    # The failing pytest run is surfaced under "Failed attempts" (a failed
    # command is an attempt that did not pass, not a proven ruled-out cause).
    assert "## Failed attempts" in report
    assert "pytest tests/test_auth.py` -> failed (exit 1)" in report


def test_old_format_session_still_renders():
    # A session whose command events lack the new fields (git snapshot,
    # redacted flag) must still load and render in every mode.
    now = utc_now()
    ts = to_iso8601(now)
    raw = {
        "session_id": "old-0000",
        "title": "Legacy session",
        "status": SessionStatus.COMPLETED.value,
        "project_root": "/repo",
        "git": {"is_repo": True, "repo_root": "/repo", "initial_sha": "a", "final_sha": "b"},
        "timestamps": {"start": ts, "end": ts},
        "events": [
            {"type": "note", "timestamp": ts, "data": {"text": "old note"}},
            {
                "type": "command",
                "timestamp": ts,
                "data": {
                    "command": "pytest",
                    "started_at": ts,
                    "ended_at": ts,
                    "duration_seconds": 0.1,
                    "exit_code": 0,
                    "classification": {
                        "is_test": True,
                        "is_verification": True,
                        "tool": "pytest",
                        "status": COMMAND_STATUS_PASSED,
                    },
                },
            },
        ],
        "summary": {"notes_count": 1, "commands_count": 1},
    }
    session = Session.from_dict(raw)
    for mode in VALID_MODES:
        report = render_report(session, mode)
        assert report.startswith("# Legacy session")
